apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mpijobs.kubeflow.org
spec:
  group: kubeflow.org
  scope: Namespaced
  names:
    plural: mpijobs
    singular: mpijob
    kind: MPIJob
    shortNames:
    - mj
    - mpij
  versions:
  - name: v2beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              slotsPerWorker:
                type: integer
                minimum: 1
              runPolicy:
                type: object
                properties:
                  cleanPodPolicy:
                    type: string
                    enum: ["None", "Running", "All"]
                    description: "Defines which worker Pods must be deleted after the Job completes"
                  ttlSecondsAfterFinished:
                    type: integer
                    minimum: 0
                    description: |
                      Defines the TTL to clean up the launcher Job.
                      Defaults to infinite. Requires kubernetes 1.21+.
                  activeDeadlineSeconds:
                    type: integer
                    minimum: 0
                    description: |
                      Defines the duration in seconds, relative to its start time, that the launcher
                      Job may be active before the system tries to terminate it. Defaults to infinite.
                  backoffLimit:
                    type: integer
                    minimum: 0
                    description: "Specifies the number of retries before marking the launcher Job as failed. Defaults to 6."
                  suspend:
                    type: boolean
              sshAuthMountPath:
                type: string
              mpiImplementation:
                type: string
                enum: ["OpenMPI", "Intel"]
              mpiReplicaSpecs:
                type: object
                properties:
                  Launcher:
                    type: object
                    properties:
                      replicas:
                        type: integer
                        minimum: 1
                        maximum: 1
                      template:
                        x-kubernetes-preserve-unknown-fields: true
                        type: object
                      restartPolicy:
                        type: string
                        enum: ["Never", "OnFailure"]
                  Worker:
                    type: object
                    properties:
                      replicas:
                        type: integer
                        minimum: 1
                      template:
                        x-kubernetes-preserve-unknown-fields: true
                        type: object
                      restartPolicy:
                        type: string
                        enum: ["Never", "OnFailure"]
                required:
                - Launcher
          status:
            type: object
            properties:
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                      enum: ["Created", "Running", "Restarting", "Succeeded", "Suspended", "Failed"]
                    status:
                      type: string
                      enum: ["True", "False", "Unknown"]
                    reason:
                      type: string
                    message:
                      type: string
                    lastUpdateTime:
                      type: string
                      format: date-time
                    lastTransitionTime:
                      type: string
                      format: date-time
              replicaStatuses:
                type: object
                properties:
                  Launcher:
                    type: object
                    properties:
                      active:
                        type: integer
                      succeeded:
                        type: integer
                      failed:
                        type: integer
                  Worker:
                    type: object
                    properties:
                      active:
                        type: integer
                      succeeded:
                        type: integer
                      failed:
                        type: integer
              startTime:
                type: string
                format: date-time
              completionTime:
                type: string
                format: date-time
              lastReconcileTime:
                type: string
                format: date-time
    subresources:
      status: {}
