apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- kubeflow.org_mpijobs.yaml
- deployment.yaml
- service-account.yaml
images:
- name: mpioperator/mpi-operator
  newName: mpioperator/mpi-operator
  newTag: latest
labels:
- includeSelectors: true
  pairs:
    app: mpi-operator
    app.kubernetes.io/component: mpijob
    app.kubernetes.io/name: mpi-operator
    kustomize.component: mpi-operator
