# coding: utf-8

"""
    mpijob

    Python SDK for MPI-Operator  # noqa: E501

    The version of the OpenAPI document: v2beta1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import mpijob
from mpijob.models.io_k8s_apimachinery_pkg_apis_meta_v1_group_version_for_discovery import IoK8sApimachineryPkgApisMetaV1GroupVersionForDiscovery  # noqa: E501
from mpijob.rest import ApiException

class TestIoK8sApimachineryPkgApisMetaV1GroupVersionForDiscovery(unittest.TestCase):
    """IoK8sApimachineryPkgApisMetaV1GroupVersionForDiscovery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test IoK8sApimachineryPkgApisMetaV1GroupVersionForDiscovery
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = mpijob.models.io_k8s_apimachinery_pkg_apis_meta_v1_group_version_for_discovery.IoK8sApimachineryPkgApisMetaV1GroupVersionForDiscovery()  # noqa: E501
        if include_optional :
            return IoK8sApimachineryPkgApisMetaV1GroupVersionForDiscovery(
                group_version = '', 
                version = ''
            )
        else :
            return IoK8sApimachineryPkgApisMetaV1GroupVersionForDiscovery(
                group_version = '',
                version = '',
        )

    def testIoK8sApimachineryPkgApisMetaV1GroupVersionForDiscovery(self):
        """Test IoK8sApimachineryPkgApisMetaV1GroupVersionForDiscovery"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
