# coding: utf-8

"""
    mpijob

    Python SDK for MPI-Operator  # noqa: E501

    The version of the OpenAPI document: v2beta1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import mpijob
from mpijob.models.io_k8s_apimachinery_pkg_apis_meta_v1_table_row import IoK8sApimachineryPkgApisMetaV1TableRow  # noqa: E501
from mpijob.rest import ApiException

class TestIoK8sApimachineryPkgApisMetaV1TableRow(unittest.TestCase):
    """IoK8sApimachineryPkgApisMetaV1TableRow unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test IoK8sApimachineryPkgApisMetaV1TableRow
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = mpijob.models.io_k8s_apimachinery_pkg_apis_meta_v1_table_row.IoK8sApimachineryPkgApisMetaV1TableRow()  # noqa: E501
        if include_optional :
            return IoK8sApimachineryPkgApisMetaV1TableRow(
                cells = [
                    None
                    ], 
                conditions = [
                    mpijob.models.io/k8s/apimachinery/pkg/apis/meta/v1/table_row_condition.io.k8s.apimachinery.pkg.apis.meta.v1.TableRowCondition(
                        message = '', 
                        reason = '', 
                        status = '', 
                        type = '', )
                    ], 
                object = mpijob.models.io/k8s/apimachinery/pkg/runtime/raw_extension.io.k8s.apimachinery.pkg.runtime.RawExtension()
            )
        else :
            return IoK8sApimachineryPkgApisMetaV1TableRow(
                cells = [
                    None
                    ],
        )

    def testIoK8sApimachineryPkgApisMetaV1TableRow(self):
        """Test IoK8sApimachineryPkgApisMetaV1TableRow"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
