# coding: utf-8

"""
    mpijob

    Python SDK for MPI-Operator  # noqa: E501

    The version of the OpenAPI document: v2beta1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import mpijob
from mpijob.models.v2beta1_job_status import V2beta1JobStatus  # noqa: E501
from mpijob.rest import ApiException

class TestV2beta1JobStatus(unittest.TestCase):
    """V2beta1JobStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V2beta1JobStatus
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = mpijob.models.v2beta1_job_status.V2beta1JobStatus()  # noqa: E501
        if include_optional :
            return V2beta1JobStatus(
                completion_time = None, 
                conditions = [
                    mpijob.models.v2beta1/job_condition.v2beta1.JobCondition(
                        last_transition_time = None, 
                        last_update_time = None, 
                        message = '', 
                        reason = '', 
                        status = '', 
                        type = '', )
                    ], 
                last_reconcile_time = None, 
                replica_statuses = {
                    'key' : mpijob.models.v2beta1/replica_status.v2beta1.ReplicaStatus(
                        active = 56, 
                        failed = 56, 
                        label_selector = None, 
                        selector = '', 
                        succeeded = 56, )
                    }, 
                start_time = None
            )
        else :
            return V2beta1JobStatus(
        )

    def testV2beta1JobStatus(self):
        """Test V2beta1JobStatus"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
