# coding: utf-8

"""
    mpijob

    Python SDK for MPI-Operator  # noqa: E501

    The version of the OpenAPI document: v2beta1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import mpijob
from mpijob.models.io_k8s_apimachinery_pkg_version_info import IoK8sApimachineryPkgVersionInfo  # noqa: E501
from mpijob.rest import ApiException

class TestIoK8sApimachineryPkgVersionInfo(unittest.TestCase):
    """IoK8sApimachineryPkgVersionInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test IoK8sApimachineryPkgVersionInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = mpijob.models.io_k8s_apimachinery_pkg_version_info.IoK8sApimachineryPkgVersionInfo()  # noqa: E501
        if include_optional :
            return IoK8sApimachineryPkgVersionInfo(
                build_date = '', 
                compiler = '', 
                emulation_major = '', 
                emulation_minor = '', 
                git_commit = '', 
                git_tree_state = '', 
                git_version = '', 
                go_version = '', 
                major = '', 
                min_compatibility_major = '', 
                min_compatibility_minor = '', 
                minor = '', 
                platform = ''
            )
        else :
            return IoK8sApimachineryPkgVersionInfo(
                build_date = '',
                compiler = '',
                git_commit = '',
                git_tree_state = '',
                git_version = '',
                go_version = '',
                major = '',
                minor = '',
                platform = '',
        )

    def testIoK8sApimachineryPkgVersionInfo(self):
        """Test IoK8sApimachineryPkgVersionInfo"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
