# coding: utf-8

"""
    mpijob

    Python SDK for MPI-Operator  # noqa: E501

    The version of the OpenAPI document: v2beta1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import mpijob
from mpijob.models.io_k8s_apimachinery_pkg_apis_meta_v1_timestamp import IoK8sApimachineryPkgApisMetaV1Timestamp  # noqa: E501
from mpijob.rest import ApiException

class TestIoK8sApimachineryPkgApisMetaV1Timestamp(unittest.TestCase):
    """IoK8sApimachineryPkgApisMetaV1Timestamp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test IoK8sApimachineryPkgApisMetaV1Timestamp
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = mpijob.models.io_k8s_apimachinery_pkg_apis_meta_v1_timestamp.IoK8sApimachineryPkgApisMetaV1Timestamp()  # noqa: E501
        if include_optional :
            return IoK8sApimachineryPkgApisMetaV1Timestamp(
                nanos = 56, 
                seconds = 56
            )
        else :
            return IoK8sApimachineryPkgApisMetaV1Timestamp(
                nanos = 56,
                seconds = 56,
        )

    def testIoK8sApimachineryPkgApisMetaV1Timestamp(self):
        """Test IoK8sApimachineryPkgApisMetaV1Timestamp"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
