{{- if .Values.rbac.namespaced.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "mpi-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "mpi-operator.name" . }}
    chart: {{ template "mpi-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end }}
