# This file shows how to run multi-node training benchmarks using an MPIJob,
# using real ImageNet data stored in Amazon EFS.
#
# It assume the ImageNet tfrecord files are stored in an EFS directory under
# `/imagenet/{train,validation}`.
apiVersion: kubeflow.org/v1alpha2
kind: MPIJob
metadata:
  name: tensorflow-benchmarks-imagenet
spec:
  slotsPerWorker: 8
  cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
          - image: mpioperator/tensorflow-benchmarks:latest
            name: tensorflow-benchmarks
            command:
              - mpirun
              - --allow-run-as-root
              - -np
              - "16"
              - -bind-to
              - none
              - -map-by
              - slot
              - -x
              - NCCL_DEBUG=INFO
              - -x
              - LD_LIBRARY_PATH
              - -x
              - PATH
              - -mca
              - pml
              - ob1
              - -mca
              - btl
              - ^openib
              - python
              - scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py
              - --data_format=NCHW
              - --batch_size=256
              - --model=resnet50
              - --optimizer=momentum
              - --variable_update=horovod
              - --nodistortions
              - --gradient_repacking=8
              - --num_epochs=90
              - --weight_decay=1e-4
              - --data_dir=/efs/imagenet/train
              - --use_fp16
              - --train_dir=/models/resnet50
    Worker:
      replicas: 2
      template:
        spec:
          containers:
          - image: mpioperator/tensorflow-benchmarks:latest
            name: tensorflow-benchmarks
            resources:
              limits:
                nvidia.com/gpu: 8
            volumeMounts:
            - mountPath: /efs
              name: efs
            - mountPath: /models
              name: models
          volumes:
            - name: efs
              nfs:
                server: fs-ab134502.efs.us-west-2.amazonaws.com
                path: /
                readOnly: true
            - name: models
              emptyDir: {}

