# Demo on how to write a pipeline run.

apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: mnist-
  namespace: tektoncd
  labels:
    pipeline: mnist-notebook
spec:
  params:
  # test-target-name, artifacts-gcs, and junit-path are required for
  # all the PipelineRuns. For tests spawned by Prow, values of these
  # params will be injected on the fly.
  #- name: test-target-name
  #  value: manual-testinig
  #- name: artifacts-gcs
  #  value: gs://kubeflow-ci-deployment/gabrielwen-testing-2
  #- name: junit-path
  #  value: artifacts/junit_manual-testing
  - name: testing-cluster-pattern
    value: 'kf-vbp-.*'
  - name: testing-cluster-location
    value: 'us-central1'
  - name: output-workspace
    value: /workspace/outputs
  resources:
  # This pull number has changes blocked on:
  # https://github.com/kubeflow/testing/pull/622
  - name: examples-repo
    resourceSpec:
      type: git
      params:
      - name: url
        value: https://github.com/kubeflow/examples.git
      - name: revision
        value: refs/pull/803/head
  - name: testing-repo
    resourceSpec:
      type: git
      params:
      - name: url
        value: https://github.com/kubeflow/testing.git
      - name: revision
        #value: master
        value: refs/pull/676/head
  pipelineRef:
    name: notebook-test