apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: kubeflow
patches:
- path: ./patch.yaml
  target:
    group: apps
    kind: Deployment
    name: mpi-operator
    version: v1
labels:
- includeSelectors: true
  pairs:
    app: mpi-operator
    app.kubernetes.io/component: mpijob
    app.kubernetes.io/name: mpi-operator
    kustomize.component: mpi-operator
