# This file shows how to run multi-node training benchmarks using an MPIJob,
# letting the operator decide on how best to allocate GPUs.
#
# In this mode, the operator assumes all nodes have the same number of GPUs.
# If `gpus` is bigger than the number of GPUs per node, then only whole nodes
# can be allocated.
#
# For example, if each node has 8 GPUs, the valid `gpus` values are:
# 1, 2, 4, 8, 16, 24, 32, ...or any multiple of 8.
#
# If you need more flexibility in allocating GPUs, you can use the alternative
# mode to specify `replicas` and GPU resource limit explicitly.
apiVersion: kubeflow.org/v1alpha1
kind: MPIJob
metadata:
  name: tensorflow-benchmarks-16
spec:
  gpus: 16
  template:
    spec:
      containers:
      - image: mpioperator/tensorflow-benchmarks:latest
        name: tensorflow-benchmarks
