# This file shows how to run multi-node training benchmarks using an MPIJob,
# specifying GPUs explicitly per replica.
apiVersion: kubeflow.org/v1alpha1
kind: MPIJob
metadata:
  name: tensorflow-benchmarks-16-custom
spec:
  replicas: 4
  template:
    spec:
      containers:
      - image: mpioperator/tensorflow-benchmarks:latest
        name: tensorflow-benchmarks
        resources:
          limits:
            nvidia.com/gpu: 4
