# coding: utf-8

"""
    mpijob

    Python SDK for MPI-Operator  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup, find_packages  # noqa: H301

with open('requirements.txt') as f:
    REQUIRES = f.readlines()

with open('test-requirements.txt') as f:
    TEST_REQUIRES = f.readlines()

setup(
	name='kubeflow-mpijob',
  	version='0.1.0',
	author="Kubeflow Authors",
	url="https://github.com/kubeflow/mpi-operator/sdk/python/v1",
	description="MPI Operator Python SDK V1",
	long_description="MPI Operator Python SDK V1",
	packages=find_packages(include=("mpijob*")),
	package_data={},
	include_package_data=False,
	zip_safe=False,
	install_requires=REQUIRES,
	tests_require=TEST_REQUIRES,
	extras_require={'test': TEST_REQUIRES}
)
